export const flashcards = [
    // 10th Kup
    { english: "High", korean: "Nopunde", category: "General", level: "10th Kup" },
    { english: "Middle", korean: "Kaunde", category: "General", level: "10th Kup" },
    { english: "Low", korean: "Najunde", category: "General", level: "10th Kup" },
    { english: "Forefist", korean: "Ap Joomuk", category: "Parts of the body", level: "10th Kup" },
    { english: "Forearm", korean: "Palmok", category: "Parts of the body", level: "10th Kup" },
    { english: "Inner", korean: "An", category: "Parts of the body", level: "10th Kup" },
    { english: "Outer", korean: "Bakat", category: "Parts of the body", level: "10th Kup" },
    { english: "Attention Stance", korean: "Charyot Sogi", category: "Stances", level: "10th Kup" },
    { english: "Parallel Stance", korean: "Narani Sogi", category: "Stances", level: "10th Kup" },
    { english: "Sitting Stance", korean: "Annun Sogi", category: "Stances", level: "10th Kup" },
    { english: "Walking Stance", korean: "Gunnun Sogi", category: "Stances", level: "10th Kup" },
    { english: "Inner Forearm Block", korean: "An Palmok Makgi", category: "Defensive Movements", level: "10th Kup" },
    { english: "Outer Forearm Block", korean: "Bakat Palmok Makgi", category: "Defensive Movements", level: "10th Kup" },
    { english: "Front Punch", korean: "Ap Jirugi", category: "Offensive Movements", level: "10th Kup" },
    // 9th Kup
    { english: "Left", korean: "Wen", category: "General", level: "9th Kup" },
    { english: "Right", korean: "Orun", category: "General", level: "9th Kup" },
    { english: "Pattern", korean: "Tul", category: "General", level: "9th Kup" },
    { english: "Ball of foot", korean: "Ap Kumchi", category: "Parts of the body", level: "9th Kup" },
    { english: "Foot sword", korean: "Balkal", category: "Parts of the body", level: "9th Kup" },
    { english: "Head", korean: "Mori", category: "Parts of the body", level: "9th Kup" },
    { english: "L stance", korean: "Niunja Sogi", category: "Stances", level: "9th Kup" },
    { english: "Rising block", korean: "Chookyo Makgi", category: "Defensive Movements", level: "9th Kup" },
    { english: "Forearm guarding block", korean: "Palmok Daebi Makgi", category: "Defensive Movements", level: "9th Kup" },
    { english: "Kick", korean: "Chagi", category: "Offensive Movements", level: "9th Kup" },
    { english: "Double punch", korean: "Doo Jirugi", category: "Offensive Movements", level: "9th Kup" },
    { english: "Front snap kick", korean: "Ap Chabusigi", category: "Offensive Movements", level: "9th Kup" },
    { english: "Knifehand strike", korean: "Sonkal Taerigi", category: "Offensive Movements", level: "9th Kup" },
    // 8th Kup
    { english: "Inward", korean: "Anaero", category: "General", level: "8th Kup" },
    { english: "Outward", korean: "Bakaero", category: "General", level: "8th Kup" },
    { english: "Palm", korean: "Sonbadak", category: "Parts of the body", level: "8th Kup" },
    { english: "Knifehand", korean: "Sonkal", category: "Parts of the body", level: "8th Kup" },
    { english: "Backfist", korean: "Dung Joomuk", category: "Parts of the body", level: "8th Kup" },
    { english: "Knifehand guarding block", korean: "Sonkal Daebi Makgi", category: "Defensive Movements", level: "8th Kup" },
    { english: "Twin forearm block", korean: "Sang Palmok Makgi", category: "Defensive Movements", level: "8th Kup" },
    { english: "Inward outer forearm block", korean: "Anaero Bakat Palmok Makgi", category: "Defensive Movements", level: "8th Kup" },
    { english: "Backfist strike", korean: "Dung Joomuk Taerigi", category: "Offensive Movements", level: "8th Kup" },
    { english: "Turning kick", "korean": "Dollyo Chagi", category: "Offensive Movements", level: "8th Kup" },
    { english: "Front backfist strike", korean: "Ap Dung Joomuk Taerigi", category: "Offensive Movements", level: "8th Kup" },
    // 7th Kup
    { english: "Straight", korean: "Sun", category: "General", level: "7th Kup" },
    { english: "Thrust", korean: "Tulgi", category: "General", level: "7th Kup" },
    { english: "Finger", korean: "Songarak", category: "Parts of the body", level: "7th Kup" },
    { english: "As a group fingertips", korean: "Sonkut", category: "Parts of the body", level: "7th Kup" },
    { english: "Fixed stance", korean: "Gojong Sogi", category: "Stances", level: "7th Kup" },
    { english: "Wedging block", korean: "Hechyo Makgi", category: "Defensive Movements", level: "7th Kup" },
    { english: "Release move", korean: "Jappyosol Tae", category: "Defensive Movements", level: "7th Kup" },
    { english: "Straight spear fingertip thrust", korean: "Sun Sonkut Tulgi", category: "Offensive Movements", level: "7th Kup" },
    { english: "Backfist side strike", korean: "Dung Joomuk Yop Taerigi", category: "Offensive Movements", level: "7th Kup" },
    { english: "Side piercing kick", korean: "Yop Cha jurigi", category: "Offensive Movements", level: "7th Kup" },
    // 6th Kup
    { english: "Back", korean: "Dwit", category: "General", level: "6th Kup" },
    { english: "Foot parts", korean: "Habansin", category: "Parts of the body", level: "6th Kup" },
    { english: "Hand parts", korean: "Sangbansin", category: "Parts of the body", level: "6th Kup" },
    { english: "Back sole", korean: "Dwit Kumchi", category: "Parts of the body", level: "6th Kup" },
    { english: "Back heel", korean: "Dwit Chook", category: "Parts of the body", level: "6th Kup" },
    { english: "Vertical stance", korean: "Soojik Sogi", category: "Stances", level: "6th Kup" },
    { english: "Closed stance", korean: "Moa Sogi", category: "Stances", level: "6th Kup" },
    { english: "Bending stance", korean: "Goburyo Sogi", category: "Stances", level: "6th Kup" },
    { english: "Circular block", korean: "Dollimyo Makgi", category: "Defensive Movements", level: "6th Kup" },
    { english: "Hooking block", korean: "Golcho Makgi", category: "Defensive Movements", level: "6th Kup" },
    { english: "Waist block", korean: "Hori Makgi", category: "Defensive Movements", level: "6th Kup" },
    { english: "Palm pushing block", korean: "Sonbadak Miro Makgi", category: "Defensive Movements", level: "6th Kup" },
    { english: "Vertical punch", korean: "Sewo Jirugi", category: "Offensive Movements", level: "6th Kup" },
    { english: "Side punch", korean: "Yop Jirugi", category: "Offensive Movements", level: "6th Kup" },
    { english: "Reverse turning kick", korean: "Bandae Dollyo Chagi", category: "Offensive Movements", level: "6th Kup" },
    { english: "Reverse side kick", korean: "Bandae Yop Chagi", category: "Offensive Movements", level: "6th Kup" },
    { english: "Reverse knifehand strike", korean: "Sonkal Dung Taerigi", category: "Offensive Movements", level: "6th Kup" },
    // 5th Kup
    { english: "Jumping", korean: "Twigi", category: "General", level: "5th Kup" },
    { english: "Elbow", korean: "Palkup", category: "Parts of the body", level: "5th Kup" },
    { english: "Knee", korean: "Moorup", category: "Parts of the body", level: "5th Kup" },
    { english: "X stance", korean: "Kyocha Sogi", category: "Stances", level: "5th Kup" },
    { english: "Double forearm block", korean: "Doo Palmok Makgi", category: "Defensive Movements", level: "5th Kup" },
    { english: "Hooking block", korean: "Golcho Makgi", category: "Defensive Movements", level: "5th Kup" },
    { english: "X fist pressing block", korean: "Kyocha Nollo Makgi", category: "Defensive Movements", level: "5th Kup" },
    { english: "Upward palm block", korean: "Ollyo Sonbadak Makgi", category: "Defensive Movements", level: "5th Kup" },
    { english: "Twin knifehand block", korean: "Sang Sonkal Makgi", category: "Defensive Movements", level: "5th Kup" },
    { english: "Upset punch", korean: "Dwijibo Jirugi", category: "Offensive Movements", level: "5th Kup" },
    { english: "Hooking kick", korean: "Golcho Chagi", category: "Offensive Movements", level: "5th Kup" },
    { english: "Flat fingertip thrust", korean: "Opun Sonkut Tulgi", category: "Offensive Movements", level: "5th Kup" },
    { english: "Crescent kick", korean: "Bandal Chagi", category: "Offensive Movements", level: "5th Kup" },
    { english: "Twin vertical punch", korean: "Sang Sewo Jirugi", category: "Offensive Movements", level: "5th Kup" },
    { english: "Mid section upset", korean: "Dwijibo", category: "General", level: "4th Kup" },
    { english: "Low section upset", korean: "Dwijibun", category: "General", level: "4th Kup" },
    { english: "Side sole", korean: "Yop Bal Badak", category: "Parts of the Body", level: "4th Kup" },
    { english: "Arc hand", korean: "Bandal Son", category: "Parts of the Body", level: "4th Kup" },
    { english: "Side fist", korean: "Yop Joomuk", category: "Parts of the Body", level: "4th Kup" },
    { english: "Rear foot stance", korean: "Dwit Bal Sogi", category: "Stances", level: "4th Kup" },
    { english: "Low stance", korean: "Nachuo Sogi", category: "Stances", level: "4th Kup" },
    { english: "X block", korean: "Kyocha Makgi", category: "Defensive Movements", level: "4th Kup" },
    { english: "Pressing block", korean: "Noollo Makgi", category: "Defensive Movements", level: "4th Kup" },
    { english: "Downward block", korean: "Naeryo Makgi", category: "Defensive Movements", level: "4th Kup" },
    { english: "U shaped block", korean: "Digutja Makgi", category: "Defensive Movements", level: "4th Kup" },
    { english: "Turning punch", korean: "Dollyo Jirugi", category: "Offensive Movements", level: "4th Kup" },
    { english: "Twin upset punch", korean: "Sang Dwijibo Jirugi", category: "Offensive Movements", level: "4th Kup" },
    { english: "Upper elbow strike", korean: "Wi Palkup Taerig", category: "Offensive Movements", level: "4th Kup" },
    { english: "Back kick", korean: "Dwit Chagi", category: "Offensive Movements", level: "4th Kup" },
    { english: "Pressing kick", korean: "Noollo Chagi", category: "Offensive Movements", level: "4th Kup" },
    { english: "Side thrust kick", korean: "Yop Cha Tulgi", category: "Offensive Movements", level: "4th Kup" },
    { english: "Twin straight forearm block", korean: "Sang Sun Palmok Makgi", category: "Defensive Movements", level: "4th Kup" },
    { english: "Reverse turning hooking kick", korean: "Bandae Dollyo Goro Chagi", category: "Offensive Movements", level: "4th Kup" },
    { english: "Joong-Gun Interpretation", korean: "Named after the patriot An Joong-Gun who assassinated Hiro Bumi Ito. The 32 movements represent Mr An's age when he was executed in Lui-Shung prison in 1910.", category: "Pattern Meaning", level: "4th Kup" },
    { english: "Red Belt Meaning", korean: "Signifies danger, cautioning the student to exercise control and warning the opponent to stay away.", category: "Belt Meaning", level: "4th Kup" },
    { english: "Flying", korean: "Twimyo", category: "General", level: "3rd Kup" },
    { english: "Upset fingertips", korean: "Dwijibun Sonkut", category: "Parts of the Body", level: "3rd Kup" },
    { english: "W shape block", korean: "San Makgi", category: "Defensive Movements", level: "3rd Kup" },
    { english: "Waving kick", korean: "Doro Chagi", category: "Offensive Movements", level: "3rd Kup" },
    { english: "Front pushing kick", korean: "Ap Cha Milgi", category: "Offensive Movements", level: "3rd Kup" },
    { english: "Upper elbow strike", korean: "Wi Palkup Taerigi", category: "Offensive Movements", level: "3rd Kup" },
    { english: "One step sparring", korean: "Ilbo Matsoki", category: "Sparring", level: "3rd Kup" },
    { english: "Toi-Gye Number of Movements", korean: "37", category: "Pattern", level: "3rd Kup" },
    { english: "Toi-Gye Interpretation", korean: "Toi-Gye is the pen name of the noted scholar Yi Hwang (16th century A.D.), an authority on neo-Confucianism. The 37 movements refer to his birthplace on the 37th degree latitude and the diagram represents 'scholar'.", category: "Pattern Meaning", level: "3rd Kup" }
];
